#include "mda_tools.hpp"

void mda_tools::WriteGroFile(const std::string& filename, const std::vector<Real3>& vecpos, const std::vector<std::string>& atomtypes, const std::vector<std::string>& resname , \
const Real3& box_size){
    const char* gro_c_string="%5d%-5s%5s%5d%8.3f%8.3f%8.3f\n";

    FILE* fp;
    fp = fopen(filename.c_str(), "w");

    int total_atom = vecpos.size();
    ASSERT(((atomtypes.size() == total_atom) && (resname.size() == total_atom)) , "The atom type and resname does not match with the number of atoms.");

    fprintf(fp, "%s\n", "Generated by Yusheng Cai");
    fprintf(fp, "\t%d\n", total_atom);

    for (int i=1;i<vecpos.size()+1;i++){
        fprintf(fp, gro_c_string, i, atomtypes[i-1].c_str(), resname[i-1].c_str(), i, vecpos[i-1][0], vecpos[i-1][1], vecpos[i-1][2]);
    }

    fprintf(fp, "\t%f %f %f", box_size[0], box_size[1], box_size[2]);
    fclose(fp);
}